
.C.o:
	/usr/bin/g++ $(CFLAGS) -c -O $<

WWBCTEST_OBJS = \
	Bchart.o \
	BchartSm.o \
	Bst.o \
	FBinaryArray.o \
	CntxArray.o \
	ChartBase.o \
	ClassRule.o \
	ECArgs.o \
	Edge.o \
	EdgeHeap.o \
	Feat.o \
	Feature.o \
	FeatureTree.o \
	Field.o \
	FullHist.o \
	GotIter.o \
	InputTree.o \
	Item.o \
	Link.o \
	Params.o \
	ParseStats.o \
	SentRep.o \
	Term.o \
	TimeIt.o \
	UnitRules.o \
	ValHeap.o \
	edgeSubFns.o \
	ewDciTokStrm.o \
	extraMain.o \
	fhSubFns.o \
	headFinder.o \
	headFinderCh.o \
	utils.o \
	MeChart.o \
	wwBCTest.o 


wwBCTest: $(WWBCTEST_OBJS)
	g++ $(CFLAGS) $(WWBCTEST_OBJS) -o wwBCTest 


PARSE_OBJS = \
	Bchart.o \
	BchartSm.o \
	Bst.o \
	FBinaryArray.o \
	CntxArray.o \
	ChartBase.o \
	ClassRule.o \
	CombineBests.o \
	ECArgs.o \
	Edge.o \
	EdgeHeap.o \
	Feat.o \
	Feature.o \
	FeatureTree.o \
	Field.o \
	FullHist.o \
	GotIter.o \
	InputTree.o \
	Item.o \
	Link.o \
	Params.o \
	ParseStats.o \
	SentRep.o \
	Term.o \
	TimeIt.o \
	UnitRules.o \
	ValHeap.o \
	edgeSubFns.o \
	ewDciTokStrm.o \
	extraMain.o \
	fhSubFns.o \
	headFinder.o \
	headFinderCh.o \
	utils.o \
	MeChart.o \
	parseIt.o 


parseIt: $(PARSE_OBJS)
	g++ $(CFLAGS) $(PARSE_OBJS) -o parseIt 


RPARSE_OBJS = \
	AnswerTree.o \
	Bchart.o \
	BchartSm.o \
	FBinaryArray.o \
	CntxArray.o \
	ChartBase.o \
	ClassRule.o \
	CombineBests.o \
	ECArgs.o \
	Edge.o \
	EdgeHeap.o \
	EgsFromTree.o \
	Feat.o \
	Feature.o \
	FeatureTree.o \
	Field.o \
	FullHist.o \
	GotIter.o \
	InputTree.o \
	Item.o \
	Params.o \
	ParseStats.o \
	SentRep.o \
	Term.o \
	TimeIt.o \
	UnitRules.o \
	edgeSubFns.o \
	ewDciTokStrm.o \
	extraMain.o \
	fhSubFns.o \
	headFinder.o \
	headFinderCh.o \
	utils.o \
	MeChart.o \
	rParse.o 


rParse: $(RPARSE_OBJS)
	g++ $(CFLAGS) $(RPARSE_OBJS) -o rParse 


FPT_OBJS = \
	ECArgs.o \
	utils.o \
	ParseStats.o \
	finPTest.o

finPTest: $(FPT_OBJS)
	g++ $(CFLAGS) $(FPT_OBJS) -o finPTest
