here=File.dirname(__FILE__)

ENV['PYTHONPATH'] = ["#{here}/src",
                     "#{here}/3rdParty/malt/malt-1.4",
                     "#{here}/3rdParty/jpype/JPype-0.5.4.1/build/lib.linux-i686-2.6/",
                    ].join(':')


def python(file)
  if ($debug_python)
    sh "gdb --args python #{file}"
  else
    sh "python #{file}"
  end
end

desc "Print the python path"
task :pythonpath do
  puts ENV["PYTHONPATH"]
end

desc "Run the test cases."
task :partial_tests  do
  #python("/usr/bin/nosetests src/stanford_parser/dependencies_test.py")
  python("/usr/bin/nosetests src/stanford_parser/parser_test.py")
end


desc "Run the test cases."
task :tests do
  sh "python /usr/bin/nosetests -v"
end

